version: '3.8'

services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: hotel_backend_dev
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb+srv://suphanatchanlek:Arm0612601997@cluster0.u8bnp.mongodb.net/
      - JWT_SECRET=suphanat30chanlek
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - hotel_network_dev

networks:
  hotel_network_dev:
    driver: bridge